sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t DeepseaPlatform/dock .

script:
  - docker run DeepseaPlatform/dock /bin/bash -c "cd coastal ; ./gradlew check"
