#!/bin/bash

DESTINATION=/tmp/coastal.zip
PROJECTDIR=../..

#------------------------------------------------------------------------------
# determine the absolute project path
#------------------------------------------------------------------------------
SAVED="`pwd`"
cd "${PROJECTDIR}" >/dev/null
PROJECTDIR="`pwd -P`"
cd "${SAVED}" >/dev/null

#------------------------------------------------------------------------------
# create a temporary directory
#------------------------------------------------------------------------------
DIR=`mktemp -d -t coastal-zip.XXXXXX`
trap "rm -rf ${DIR}" EXIT

#------------------------------------------------------------------------------
# create the zip file
#------------------------------------------------------------------------------
mkdir -p ${DIR}/coastal/coastal
cp -r ${PROJECTDIR}/build/install/coastal/lib ${DIR}/coastal/coastal/
cp ${PROJECTDIR}/extra/svcomp/coastal-sv-comp ${DIR}/coastal/
cp ${PROJECTDIR}/LICENSE.md ${DIR}/coastal/LICENSE
SAVED="`pwd`"
cd ${DIR} >/dev/null
rm -f ${DESTINATION} >/dev/null
zip -r ${DESTINATION} coastal
cd "${SAVED}" >/dev/null

