#-------------------------------------------------------------------------------
# COASTAL Jekyll site
#-------------------------------------------------------------------------------

title: COASTAL
email: jacogeld+coastal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/coastal"
#url: "https://www.cs.sun.ac.za"
url: ""
twitter_username: coastal
github_username:  coastal
markdown: kramdown
include: ["_pages", "coastal.dtd"]
exclude: ["copyapi.sh", "Gemfile", "Gemfile.lock", "_pages/userguide/figures"]
plugins:
  - jekyll-feed
