source "https://rubygems.org"
gem "jekyll", "~> 3.8.5"
gem "ffi", "~> 1.9", ">= 1.9.10"
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "jekyll-tidy"
