source "https://rubygems.org"
gem "jekyll", ">= 3.6.3"
gem "ffi", ">= 1.9.24"
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
